export const gec = [
  {
    type: "gec",
    courseCode: "BT PPT 409A",
    courseName: "Basics of Printing and Packaging Materials",
    CourseCredits: 4,
    department: " Printing and Packaging Materials",
    teacher: "suman kumari",
    sem: 4,
    eligible: "ug",
    seats: 40,
  },
  {
    type: "gec2",
    courseCode: "BT PPT 409A",
    courseName: "Printing and Packaging Materials",
    CourseCredits: 4,
    department: " Printing and Packaging Materials",
    teacher: "suman kumari",
    sem: 4,
    eligible: "ug",
    seats: 40,
  },
  {
    type: "gec3",
    courseCode: "BT PPT 409A",
    courseName: "Printing and Packaging Materials",
    CourseCredits: 4,
    department: " Printing and Packaging Materials",
    teacher: "suman kumari",
    sem: 4,
    eligible: "ug",
    seats: 40,
  },
  {
    type: "gec4",
    courseCode: "BT PPT 409A",
    courseName: "Printing and Packaging Materials",
    CourseCredits: 4,
    department: " Printing and Packaging Materials",
    teacher: "suman kumari",
    sem: 4,
    eligible: "ug",
    seats: 40,
  },
  {
    type: "gec5",
    courseCode: "BT PPT 409A",
    courseName: "Printing and Packaging Materials",
    CourseCredits: 4,
    department: " Printing and Packaging Materials",
    teacher: "suman kumari",
    sem: 4,
    eligible: "ug",
    seats: 40,
  },
];
